name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        env:
          ESLINT_USE_FLAT_CONFIG: 'false'
          TSESTREE_NO_WARN_ON_UNSUPPORTED_TYPESCRIPT_VERSION: '1'
        run: npm run lint -- --max-warnings=0 --config .eslintrc.js

  e2e-smoke:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Prepare sample audio fixture
        run: |
          mkdir -p tmp
          if [ -f fixtures/sample-command.b64.txt ]; then
            base64 --decode fixtures/sample-command.b64.txt > tmp/sample-command.wav
          else
            node scripts/make-sample-wav.js tmp/sample-command.wav
          fi

      - name: Run speech E2E smoke test
        run: bash scripts/ci-e2e-smoke.sh

      - name: Upload speech E2E artifacts
        uses: actions/upload-artifact@v4
        with:
          name: e2e-smoke-artifacts
          path: artifacts/e2e-smoke
          if-no-files-found: warn
